name: Daily Commit Workflow

on:
  schedule:
    - cron: '17 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  commit-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Make dummy file update
        run: echo "$(date)" >> daily-log.txt

      - name: Commit with email 24f1001434@ds.study.iitm.ac.in
        run: |
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "24f1001434@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push origin main
