name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Email
        run: echo "Hello, world! My email is 24f1001434@ds.study.iitm.ac.in"
